# Generated by Django 4.1.7 on 2023-03-02 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_album_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.album'),
        ),
    ]
