# Generated by Django 4.1.7 on 2023-03-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_record_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='models',
        ),
        migrations.AddField(
            model_name='song',
            name='review',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='length',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='artist',
            name='country_of_origin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='country_of_origin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='pressing_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
