# Generated by Django 4.1.7 on 2023-03-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_song_models_song_review_alter_album_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='composer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.CharField(max_length=5),
        ),
    ]
