# Generated by Django 4.1.7 on 2023-03-03 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_album_my_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='channels',
            field=models.CharField(choices=[('STEREO', 'Stereo'), ('MONO', 'Mono')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='my_review',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.collection'),
        ),
    ]
