# Generated by Django 4.1.7 on 2023-03-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_record_channels_alter_album_my_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='channels',
            field=models.CharField(choices=[('Stereo', 'Stereo'), ('Mono', 'Mono')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='cover_rating',
            field=models.CharField(choices=[('Mint', 'M'), ('Near Mint', 'NM'), ('Very Good +', 'VG+'), ('Very Good', 'VG'), ('Good', 'G'), ('Poor', 'P')], max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='disc_rating',
            field=models.CharField(choices=[('Mint', 'M'), ('Near Mint', 'NM'), ('Very Good +', 'VG+'), ('Very Good', 'VG'), ('Good', 'G'), ('Poor', 'P')], max_length=20),
        ),
    ]
